# Generated by Django 5.0.2 on 2024-02-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_contestcriterion_contest_and_more'),
        ('core', '0006_contest_country'),
        ('member_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='contest_criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.contestcriterion'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_person_points', to='core.contestperson'),
        ),
    ]
