# Generated by Django 4.1.3 on 2023-01-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='units_scored',
            field=models.PositiveIntegerField(default=0, help_text='Number in case of Number Template, 0 and 1 for the Boolean Template, 0 (empty) and 1 (filled) for other templates'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='point_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
