# Generated by Django 4.2 on 2024-01-06 17:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxPointRecord',
            fields=[
                ('pointrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_panel.pointrecord')),
                ('checked', models.BooleanField(verbose_name=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('member_panel.pointrecord',),
        ),
        migrations.CreateModel(
            name='MultiCheckboxPointRecord',
            fields=[
                ('pointrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_panel.pointrecord')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('member_panel.pointrecord',),
        ),
        migrations.CreateModel(
            name='NumberPointRecord',
            fields=[
                ('pointrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_panel.pointrecord')),
                ('score', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('member_panel.pointrecord',),
        ),
        migrations.CreateModel(
            name='RadioPointRecord',
            fields=[
                ('pointrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member_panel.pointrecord')),
                ('choice', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('member_panel.pointrecord',),
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='units_scored',
        ),
    ]
