# Generated by Django 4.2 on 2024-01-15 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 34, 59, 777470)),
        ),
    ]
