# Generated by Django 4.2 on 2024-01-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0002_alter_pointrecord_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='record_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
