# Generated by Django 4.1.3 on 2023-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0002_pointrecord_units_scored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='units_scored',
            field=models.PositiveIntegerField(default=0, help_text='point record help text'),
        ),
    ]
