# Generated by Django 4.2 on 2024-01-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0002_checkboxpointrecord_multicheckboxpointrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberpointrecord',
            old_name='score',
            new_name='number',
        ),
    ]
