# Generated by Django 4.2 on 2024-01-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contest_announcements'),
        ('admin_panel', '0003_alter_contestcriterion_activate_on_datetime'),
        ('member_panel', '0003_rename_score_numberpointrecord_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 12, 39, 27, 15351)),
        ),
        migrations.AlterField(
            model_name='numberpointrecord',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='point_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='record_date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
        migrations.AlterField(
            model_name='radiopointrecord',
            name='choice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinputpointrecord',
            name='user_input',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='pointrecord',
            unique_together={('person', 'contest_criterion', 'record_date')},
        ),
    ]
