# Generated by Django 4.2 on 2024-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_panel', '0003_alter_pointrecord_record_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='record_date',
            field=models.DateField(),
        ),
    ]
