FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install PostgreSQL and Gunicorn
RUN apt-get update && apt-get install -y libpq-dev postgresql-client netcat gettext
RUN pip install gunicorn
RUN pip install psycopg2-binary

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Copy gunicorn configuration file and start script
COPY ./gunicorn .

RUN chmod +x  ./start_server.sh
RUN chmod +x  ./entrypoint.sh

# Run entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]
