# Generated by Django 4.0.1 on 2022-01-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('code', models.IntegerField(default=9285)),
                ('name', models.CharField(default='', max_length=30)),
                ('show_standings', models.BooleanField(default=True)),
                ('readonly_mode', models.BooleanField(default=False, help_text='Stop scoring points and only show scored points')),
            ],
        ),
        migrations.CreateModel(
            name='PointFormat',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=64)),
                ('html', models.TextField(default='')),
            ],
        ),
    ]
