# Generated by Django 4.0.1 on 2022-01-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.IntegerField(default=6827),
        ),
    ]
