# Generated by Django 5.2.8 on 2026-02-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
    ]
