# Generated by Django 4.1.3 on 2023-01-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contestpersongroups',
            name='unique_group_person',
        ),
        migrations.AddConstraint(
            model_name='contestpersongroups',
            constraint=models.UniqueConstraint(fields=('contest_person_id', 'group_id'), name='unique_group_person', violation_error_message='A person can be a Group member or a Group Admin'),
        ),
    ]
