# Generated by Django 4.1.3 on 2023-01-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contestpersongroups_unique_group_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestperson',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contest'),
        ),
    ]
