# Generated by Django 4.2 on 2024-02-16 22:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contest_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('main_contact_full_name', models.CharField(max_length=128)),
                ('main_contact_phone_number', models.CharField(max_length=128)),
                ('main_contact_email', models.CharField(max_length=128)),
                ('contest_country', django_countries.fields.CountryField(max_length=2)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
            ],
        ),
    ]
