# Generated by Django 4.1.3 on 2023-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contestperson_contest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contestperson',
            name='unique_contest_person',
        ),
        migrations.RemoveConstraint(
            model_name='contestpersongroups',
            name='unique_group_person',
        ),
        migrations.AlterField(
            model_name='contest',
            name='readonly_mode',
            field=models.BooleanField(default=False, help_text='readonly_mode'),
        ),
        migrations.AlterField(
            model_name='contestperson',
            name='contest_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'member'), (2, 'admin'), (3, 'super_admin'), (4, 'read_only_member'), (5, 'pending_member'), (6, 'deactivated')], default=1),
        ),
        migrations.AddConstraint(
            model_name='contestperson',
            constraint=models.UniqueConstraint(fields=('contest_id', 'person_id'), name='unique_contest_person', violation_error_message='person exists in contest'),
        ),
        migrations.AddConstraint(
            model_name='contestpersongroups',
            constraint=models.UniqueConstraint(fields=('contest_person_id', 'group_id'), name='unique_group_person', violation_error_message='person is member of group'),
        ),
    ]
