# Generated by Django 4.2 on 2024-02-16 23:03

import core.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='days_to_record_in_past',
            field=models.IntegerField(default=1, help_text='if zero then disabled'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='wirdLogo.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=core.models.upload_location),
        ),
    ]
