# Generated by Django 4.1.3 on 2023-03-16 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contestperson_unique_contest_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='announcements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
    ]
