# Generated by Django 4.2.10 on 2024-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contest_days_to_record_in_past_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='days_to_record_in_past',
            field=models.PositiveSmallIntegerField(default=1, help_text='if zero then disabled'),
        ),
    ]
