# Generated by Django 4.1.3 on 2023-03-18 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contest_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='announcements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
        ),
    ]
