# Generated by Django 5.0.2 on 2024-02-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contest_days_to_record_in_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='country',
            field=models.CharField(default='', max_length=128),
        ),
    ]
