# Generated by Django 4.0.1 on 2022-05-22 21:02

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compAdmin', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('generaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_photo', models.ImageField(blank=True, upload_to=student.models.upload_location)),
                ('read_only', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_students', to='compAdmin.compgroup')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'default_related_name': 'competition_students',
            },
            bases=('core.generaluser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_scored_units', models.IntegerField(default=0)),
                ('ramadan_record_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('user_input', models.TextField(blank=True, default='', max_length=512)),
                ('point_total', models.IntegerField(default=0)),
                ('point_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compAdmin.pointtemplate')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_points', to='student.studentuser')),
            ],
            options={
                'ordering': ('-ramadan_record_date',),
            },
        ),
    ]
