# Generated by Django 4.0.1 on 2022-05-22 21:02

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompAdmin',
            fields=[
                ('generaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('permissions', models.CharField(default='0,0,0,0,0', max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('is_super_admin', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'competition_admins',
            },
            bases=('core.generaluser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=32)),
                ('position', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_sections', to='core.competition')),
            ],
        ),
        migrations.CreateModel(
            name='PointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('order_in_section', models.IntegerField()),
                ('custom_days', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('label', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
                ('form_type', models.CharField(choices=[('num', 'Number'), ('chk', 'Check Box'), ('oth', 'Other (Needs to be reviewed by the admin)')], default='num', max_length=3)),
                ('upper_units_bound', models.IntegerField(default=1)),
                ('lower_units_bound', models.IntegerField(default=0)),
                ('points_per_unit', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_point_templates', to='core.competition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_sections', to='compAdmin.section')),
            ],
            options={
                'ordering': ('section__position', 'order_in_section'),
            },
        ),
        migrations.CreateModel(
            name='CompGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('announcements', models.TextField(blank=True, default='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_groups', to='compAdmin.compadmin')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_groups', to='core.competition')),
            ],
        ),
    ]
