# Generated by Django 4.0.1 on 2022-01-18 02:02

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superAdmin', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superAdmin.competition')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=32)),
                ('position', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PointTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('custom_days', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('label', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
                ('points_amount', models.IntegerField(default=0)),
                ('upper_points_bound', models.IntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superAdmin.competition')),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superAdmin.pointformat')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compAdmin.section')),
            ],
        ),
        migrations.CreateModel(
            name='CompGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('announcements', models.TextField(default='')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compAdmin.compadmin')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superAdmin.competition')),
                ('extra_challenges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compAdmin.pointtemplate')),
            ],
        ),
    ]
