# Generated by Django 4.1.3 on 2022-12-26 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_in_section', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('custom_days', models.CharField(blank=True, max_length=300)),
                ('label', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ('section__position', 'order_in_section'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=32)),
                ('position', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxPointTemplate',
            fields=[
                ('pointtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.pointtemplate')),
                ('points_if_done', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.pointtemplate',),
        ),
        migrations.CreateModel(
            name='NumberPointTemplate',
            fields=[
                ('pointtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.pointtemplate')),
                ('upper_units_bound', models.IntegerField(default=5)),
                ('lower_units_bound', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_per_unit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.pointtemplate',),
        ),
    ]
