# Generated by Django 4.2 on 2024-01-23 07:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('order_in_section', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('activate_on_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
                ('deactivate_on_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ContestPersonGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'member')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('announcements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=128), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=120)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxCriterion',
            fields=[
                ('contestcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.contestcriterion')),
                ('checked_label', models.CharField(default='', max_length=15)),
                ('unchecked_label', models.CharField(default='', max_length=15)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.contestcriterion',),
        ),
        migrations.CreateModel(
            name='MultiCheckboxCriterion',
            fields=[
                ('contestcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.contestcriterion')),
                ('options', models.JSONField()),
                ('partial_points', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.contestcriterion',),
        ),
        migrations.CreateModel(
            name='NumberCriterion',
            fields=[
                ('contestcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.contestcriterion')),
                ('lower_bound', models.IntegerField(default=0)),
                ('upper_bound', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.contestcriterion',),
        ),
        migrations.CreateModel(
            name='RadioCriterion',
            fields=[
                ('contestcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.contestcriterion')),
                ('options', models.JSONField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.contestcriterion',),
        ),
        migrations.CreateModel(
            name='UserInputCriterion',
            fields=[
                ('contestcriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.contestcriterion')),
                ('allow_multiline', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('admin_panel.contestcriterion',),
        ),
    ]
