# Generated by Django 4.1.3 on 2022-12-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_sections', to='core.contest'),
        ),
        migrations.AddField(
            model_name='pointtemplate',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_point_templates', to='core.contest'),
        ),
        migrations.AddField(
            model_name='pointtemplate',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pointtemplate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.section'),
        ),
    ]
