# Generated by Django 4.2 on 2024-01-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_sections', to='core.contest'),
        ),
        migrations.AddField(
            model_name='group',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contest'),
        ),
        migrations.AddField(
            model_name='contestpersongroup',
            name='contest_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contestperson'),
        ),
        migrations.AddField(
            model_name='contestpersongroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.group'),
        ),
        migrations.AddField(
            model_name='contestcriterion',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contest'),
        ),
        migrations.AddField(
            model_name='contestcriterion',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contestcriterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.section'),
        ),
        migrations.AddConstraint(
            model_name='contestpersongroup',
            constraint=models.UniqueConstraint(fields=('contest_person_id', 'group_id'), name='unique_group_person', violation_error_message='person is member of group'),
        ),
    ]
