# Generated by Django 5.2.8 on 2026-02-26 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('core', '0002_person_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('member_ids', models.JSONField(blank=True, help_text='List of ContestPerson UUIDs', null=True)),
                ('members_from', models.IntegerField(blank=True, help_text='Start of member range (1-indexed)', null=True)),
                ('members_to', models.IntegerField(blank=True, help_text='End of member range (1-indexed, inclusive)', null=True)),
                ('serialized_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='core.contest')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='core.contestperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
