# Generated by Django 4.2 on 2024-02-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestpersongroup',
            name='contest_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contestperson'),
        ),
        migrations.AlterField(
            model_name='contestpersongroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.group'),
        ),
    ]
