# Generated by Django 4.2 on 2024-01-06 17:48

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcriterion',
            name='activate_on_datetime',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), blank=True, default=list, size=None),
        ),
    ]
