# Generated by Django 4.2 on 2024-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbercriterion',
            name='bounds',
        ),
        migrations.AddField(
            model_name='numbercriterion',
            name='lower_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numbercriterion',
            name='upper_bound',
            field=models.IntegerField(default=20),
        ),
    ]
