# Generated by Django 4.1.3 on 2023-01-02 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxpointtemplate',
            name='points_if_done',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointtemplate',
            name='custom_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None),
        ),
    ]
