# Generated by Django 4.1.3 on 2023-03-18 07:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_checkboxpointtemplate_points_if_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtemplate',
            name='custom_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=[], size=None),
        ),
    ]
