# Generated by Django 4.2 on 2024-01-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_numbercriterion_bounds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestpersongroup',
            old_name='uuid',
            new_name='id',
        ),
    ]
