# Generated by Django 5.2.8 on 2026-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_exportjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportjob',
            name='members_from',
        ),
        migrations.RemoveField(
            model_name='exportjob',
            name='members_to',
        ),
        migrations.AddField(
            model_name='exportjob',
            name='all_members',
            field=models.BooleanField(default=False, help_text='Export all contest members'),
        ),
    ]
