# Generated by Django 5.0.2 on 2024-02-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_group_announcements'),
        ('core', '0006_contest_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcriterion',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest'),
        ),
        migrations.AlterField(
            model_name='contestcriterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest'),
        ),
        migrations.AlterField(
            model_name='section',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_sections', to='core.contest'),
        ),
    ]
