# Generated by Django 5.2.8 on 2026-02-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_exportjob_members_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
