# Generated by Django 5.2.8 on 2026-02-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_exportjob_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('archived', 'Archived'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
